In [4]:
# Numpy fundamentals
import numpy as np
# Create a number ndarray
scores=np.array([12,23,45,6,7,89,9])
print(scores)

# Chaecking the numpy version
print(np.__version__)

[12 23 45  6  7 89  9]
2.4.6


In [17]:
# Craeting arrays of different dimentions
# 0-D array
a=np.array(10)
print(a)
print('------------------------------------------------------------------------')
# 1-D Array
b=np.array([10,20,30,40,50,60])
print(b)
print('------------------------------------------------------------------------')
# 2-D array
c=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(c)
print('------------------------------------------------------------------------')
# 3- D Array
d=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(d)
print('------------------------------------------------------------------------')
# Checking the number of dimension in array
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

# Creating higher dimention arrays
e=np.array([34,23,14,15], ndmin=5)
print(e)


10
------------------------------------------------------------------------
[10 20 30 40 50 60]
------------------------------------------------------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
------------------------------------------------------------------------
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
------------------------------------------------------------------------
0
1
2
3
[[[[[34 23 14 15]]]]]


In [25]:
# Array Indexing
scores1=np.array([12,23,45,6,7,89,9])
# Accessing the first element
access1=scores1[0]
print(access1)
access2=scores1[2]
print(access2)

# 2-D array
scores3=np.array([[1,2,3,4,5],[6,7,8,9,10]])
access3=scores3[1,1]
access4=scores3[0,2]
print(access3)
print(access4)

# 3-D array
scores4=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
# Accessing 3-D arrays
access5=scores4[1,0,1]
print(access5)

12
45
7
3
10


In [29]:
# Slicing arrays
scores6=np.array([12,23,45,6,7,89,9])
slice=scores6[2:5]
print(slice)
slice2=scores6[2:]
print(slice2)
slice3=scores6[:4]
print(slice3)
slice4=scores6[-1]
print(slice4)

[45  6  7]
[45  6  7 89  9]
[12 23 45  6]
9


In [31]:
# Copying an array
arr=np.array([1,2,3,6,5])
x=arr.copy()
x[1]=45
print(arr)
print(x)

[1 2 3 6 5]
[ 1 45  3  6  5]


In [33]:
# Creating an array view
arr1=np.array([6,7,8,9,10])
y=arr1.view()
y[1]=30
print(arr1)
print(y)

# Checking if an array owns the data
print(x.base)
print(y.base)

[ 6 30  8  9 10]
[ 6 30  8  9 10]
None
[ 6 30  8  9 10]


In [41]:
# Finding out the number of elements in an array
arr2=np.array([1,2,3,4,5,6,7])
shape=arr2.shape
print(shape)

arr3=np.array([[1,2,3,4,5],[6,7,8,9,10]])
shape1=arr3.shape
print(shape1)

arr4=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
shape2=arr4.shape
print(shape2)
print(arr4.ndim)

(7,)
(2, 5)
(2, 2, 4)
3


In [43]:
# Reshaping array
arr5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshape=arr5.reshape(4,3)
print(reshape)

reshape1=arr5.reshape(2,3,2)
print(reshape1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [44]:
# Iterating through an array
arr6 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

for x in arr6:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [45]:
# Iterating 2D array 
arr7=np.array([[1,2,3,4,5],[10,20,30,40,50]])

for y in arr7:
    print(y)

[1 2 3 4 5]
[10 20 30 40 50]


In [47]:
# Iterating a 3D array
arr8=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for z in arr8:
    print(z)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [51]:
# Joining arrays
c=np.array([2,3,4,5,6])
d=np.array([7,8,9,10,11])

# Joining arrays using concatenation method
e=np.concatenate((c,d))
print(e)

# Joining 2D arrays
f=np.array([[1,2,3,4],[5,6,7,8]])
g=np.array([[10,20,30,40],[50,60,70,80]])

h=np.concatenate((f,g), axis=1)
print(h)

[ 2  3  4  5  6  7  8  9 10 11]
[[ 1  2  3  4 10 20 30 40]
 [ 5  6  7  8 50 60 70 80]]


In [57]:
# Joining arrays using stack method
AB=np.array([3,4,5,6,7])
CD=np.array([9,7,6,4,3])

EF=np.stack((AB,CD))
print(EF)

# JOINING 2D ARRAYS
GH=np.array([[12,23,34,45],[65,45,36,76]])
IJ=np.array([[1,2,3,4],[0,9,8,7]])

KH=np.dstack((GH,IJ))
print(KH)

[[3 4 5 6 7]
 [9 7 6 4 3]]
[[[12  1]
  [23  2]
  [34  3]
  [45  4]]

 [[65  0]
  [45  9]
  [36  8]
  [76  7]]]


In [58]:
# Splitting arrays
ZH=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
KG=np.array_split(ZH,3)
print(KG)

[array([[[1, 2, 3],
        [4, 5, 6]]]), array([[[ 7,  8,  9],
        [10, 11, 12]]]), array([], shape=(0, 2, 3), dtype=int64)]


In [59]:
# Serching array
H=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
J=np.where(H==6)
print(J)

(array([0]), array([1]), array([2]))


In [60]:
# Sorting array
H=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
N=np.sort(H)
print(N)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
